chore: create final script

diff --git a/soft b/soft
--- a/soft
+++ b/soft
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.12 (https://bashly.dev)
+# This script was generated by bashly 1.3.3 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -288,7 +288,7 @@ install_code() {
     echo "code already installed"
   else
     sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
-    echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
+    echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
     dnf check-update
     sudo dnf -y install code
   fi
@@ -298,11 +298,12 @@ install_docker() {
   if $(check_dnf_package docker-ce); then
     echo "docker already installed"
   else
-    sudo dnf -y install dnf-plugins-core
-    sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.rep
+    sudo dnf -y install dnf-plugins-core dnf5-plugins
+    sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
     sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
-    sudo usermod -aG docker $USER
+    sudo usermod -aG docker "$USER"
     newgrp docker
+    sudo systemctl enable --now docker
   fi
 }
 
@@ -310,8 +311,17 @@ install_gh() {
   if $(check_dnf_package gh); then
     echo "gh already installed"
   else
-    sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
+    sudo dnf -y install dnf-plugins-core dnf5-plugins
+    sudo dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo
     sudo dnf install gh --repo gh-cli
+  fi
+}
+
+install_navi() {
+  if $(check_file "${HOME}/.local/bin/navi"); then
+    echo "navi already installed"
+  else
+    BIN_DIR="$HOME/.local/bin" bash <(curl -sL https://raw.githubusercontent.com/denisidoro/navi/master/scripts/install)
   fi
 }
 
@@ -344,6 +354,7 @@ soft_list_command() {
       [code]="check_dnf_package"
       [docker-ce]="check_dnf_package"
       [zoxide]="check_file ${HOME}/.local/bin/zoxide"
+      [navi]="check_file ${HOME}/.local/bin/navi"
       [jetbrains-toolbox]="check_file ${HOME}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
     )
 
@@ -415,6 +426,7 @@ soft_install_command() {
     code|\
     docker|\
     gh|\
+    navi|\
     jetbrains-toolbox)
       eval "install_${program}"
       ;;
@@ -443,6 +455,7 @@ soft_install_all_command() {
   install_code
   install_docker
   install_gh
+  install_navi
   install_jetbrains-toolbox
 
 }
@@ -716,6 +729,8 @@ run() {
 }
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  # :command.start
+  command_line_args=("$@")
   initialize
-  run "$@"
+  run "${command_line_args[@]}"
 fi
