feat: change command from `soft` to `sx`

diff --git a/sx b/sx
--- a/sx
+++ b/sx
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.3.3 (https://bashly.dev)
+# This script was generated by bashly 1.3.8 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -16,13 +16,13 @@ version_command() {
 }
 
 # :command.usage
-soft_usage() {
-  printf "soft - Personal Fedora installer\n\n"
+sx_usage() {
+  printf "sx - Personal Fedora installer\n\n"
 
   printf "%s\n" "Usage:"
-  printf "  soft COMMAND\n"
-  printf "  soft [COMMAND] --help | -h\n"
-  printf "  soft --version | -v\n"
+  printf "  sx COMMAND\n"
+  printf "  sx [COMMAND] --help | -h\n"
+  printf "  sx --version | -v\n"
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
@@ -33,6 +33,7 @@ soft_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -45,27 +46,28 @@ soft_usage() {
 
     # :command.usage_examples
     printf "%s\n" "Examples:"
-    printf "  soft ls\n"
-    printf "  soft install yakuake\n"
-    printf "  soft install-all\n"
+    printf "  sx ls\n"
+    printf "  sx install yakuake\n"
+    printf "  sx install-all\n"
     echo
 
   fi
 }
 
 # :command.usage
-soft_list_usage() {
-  printf "soft list - List all programs\n\n"
+sx_list_usage() {
+  printf "sx list - List all programs\n\n"
   printf "Alias: ls\n"
   echo
 
   printf "%s\n" "Usage:"
-  printf "  soft list [OPTIONS]\n"
-  printf "  soft list --help | -h\n"
+  printf "  sx list [OPTIONS]\n"
+  printf "  sx list --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -83,18 +85,19 @@ soft_list_usage() {
 }
 
 # :command.usage
-soft_install_usage() {
-  printf "soft install - Install given program\n\n"
+sx_install_usage() {
+  printf "sx install - Install given program\n\n"
   printf "Alias: i\n"
   echo
 
   printf "%s\n" "Usage:"
-  printf "  soft install PROGRAM\n"
-  printf "  soft install --help | -h\n"
+  printf "  sx install PROGRAM\n"
+  printf "  sx install --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -114,18 +117,19 @@ soft_install_usage() {
 }
 
 # :command.usage
-soft_install_all_usage() {
-  printf "soft install-all - Install all programs\n\n"
+sx_install_all_usage() {
+  printf "sx install-all - Install all programs\n\n"
   printf "Alias: all\n"
   echo
 
   printf "%s\n" "Usage:"
-  printf "  soft install-all\n"
-  printf "  soft install-all --help | -h\n"
+  printf "  sx install-all\n"
+  printf "  sx install-all --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -170,6 +174,8 @@ normalize_input() {
 
 # :command.inspect_args
 inspect_args() {
+  local k
+
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
@@ -353,7 +359,7 @@ install_jetbrains-toolbox() {
 
 # :command.command_functions
 # :command.function
-soft_list_command() {
+sx_list_command() {
 
   # src/list_command.sh
   status=${args[--status]}
@@ -424,7 +430,7 @@ soft_list_command() {
 }
 
 # :command.function
-soft_install_command() {
+sx_install_command() {
 
   # src/install_command.sh
   program=${args[program]}
@@ -458,7 +464,7 @@ soft_install_command() {
 }
 
 # :command.function
-soft_install_all_command() {
+sx_install_all_command() {
 
   # src/install_all_command.sh
   # Simple software
@@ -481,6 +487,8 @@ soft_install_all_command() {
 
 # :command.parse_requirements
 parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -492,7 +500,7 @@ parse_requirements() {
 
       --help | -h)
         long_usage=yes
-        soft_usage
+        sx_usage
         exit
         ;;
 
@@ -512,27 +520,27 @@ parse_requirements() {
     list | ls)
       action="list"
       shift
-      soft_list_parse_requirements "$@"
+      sx_list_parse_requirements "$@"
       shift $#
       ;;
 
     install | i)
       action="install"
       shift
-      soft_install_parse_requirements "$@"
+      sx_install_parse_requirements "$@"
       shift $#
       ;;
 
     install-all | all)
       action="install-all"
       shift
-      soft_install_all_parse_requirements "$@"
+      sx_install_all_parse_requirements "$@"
       shift $#
       ;;
 
     # :command.command_fallback
     "")
-      soft_usage >&2
+      sx_usage >&2
       exit 1
       ;;
 
@@ -567,14 +575,16 @@ parse_requirements() {
 }
 
 # :command.parse_requirements
-soft_list_parse_requirements() {
+sx_list_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        soft_list_usage
+        sx_list_usage
         exit
         ;;
 
@@ -619,14 +629,16 @@ soft_list_parse_requirements() {
 }
 
 # :command.parse_requirements
-soft_install_parse_requirements() {
+sx_install_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        soft_install_usage
+        sx_install_usage
         exit
         ;;
 
@@ -669,7 +681,7 @@ soft_install_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['program']+x} ]]; then
-    printf "missing required argument: PROGRAM\nusage: soft install PROGRAM\n" >&2
+    printf "missing required argument: PROGRAM\nusage: sx install PROGRAM\n" >&2
 
     exit 1
   fi
@@ -677,14 +689,16 @@ soft_install_parse_requirements() {
 }
 
 # :command.parse_requirements
-soft_install_all_parse_requirements() {
+sx_install_all_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        soft_install_all_usage
+        sx_install_all_usage
         exit
         ;;
 
@@ -741,9 +755,9 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
-    "list") soft_list_command ;;
-    "install") soft_install_command ;;
-    "install-all") soft_install_all_command ;;
+    "list") sx_list_command ;;
+    "install") sx_install_command ;;
+    "install-all") sx_install_all_command ;;
   esac
 }
 
